name: Run Data Migrator

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  run-data-migrator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Run Data Migrator
      run: go run src/learn123.datamigrator/main.go